config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  root 'charities#index'
  get "/charities", to: "charities#index"

  resources :charities do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]

  namespace :admin do
    root 'home#index'
    resources :users
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  has_rich_text :description
  has_one_attached :logo
  has_many_attached :images

  validates :title, presence: true, length: {minimum: 5}, uniqueness: true
  validates :tax_id_number, uniqueness: true
  validates :mission, presence: true
  validates :address1, :city, :state, presence: true
  validates :postal_code, presence: true, numericality: true, length: {is: 6}
  validates :phone, presence: true, length: {minimum: 6, maximum: 12}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: %i[show edit update destroy]

  # GET /charities or /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1 or /charities/1.json
  def show
    @charity = Charity.find(params[:id])
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
    @charity = Charity.find(params[:id])
  end

  # POST /charities or /charities.json
  def create
    @charity = Charity.new(charity_params)
    session[:charity_id] = @charity.id

    respond_to do |format|
      if @charity.save
        format.html { redirect_to charity_url(@charity), notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1 or /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to charity_url(@charity), notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1 or /charities/1.json
  def destroy
    @charity.destroy

    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'The page you requested does not exist'
      redirect_to charities_path
    end

    # Only allow a list of trusted parameters through.
    def charity_params
      params.require(:charity).permit(:title, :tax_id_number, :tax_exempt_status, :organization_type, :mission, :description, :address1, :address2, :city, :state, :postal_code, :phone, :email, :website, :published, :approved, :logo, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Charityplaza™ - Charity information portal"
    if page_title.empty?
      default_title
    else
      "#{page_title} | #{default_title}"
    end
  end

  def time_format(charity_date)
    charity_date.strftime("%e %b %Y %H:%M:%S%p")
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/charities/_charity.html.erb
<div id="<%= dom_id charity %>">

  <% if charity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(charity.errors.count, "error") %> prohibited saving this charity.</h2>
        <ul>
          <%= charity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <h4>
    <strong>Title:</strong>
    <%= link_to charity.title, charity %>
  </h4>

  <p>
    <strong>Tax id number:</strong>
    <%= charity.tax_id_number %>
  </p>

  <p>
    <strong>Tax exempt status:</strong>
    <%= charity.tax_exempt_status %>
  </p>

  <p>
    <strong>Organization type:</strong>
    <%= charity.organization_type %>
  </p>

  <p>
    <strong>Mission:</strong>
    <%= charity.mission %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= charity.description %>
  </p>

  <p>
    <strong>Address1:</strong>
    <%= charity.address1 %>
  </p>

  <p>
    <strong>Address2:</strong>
    <%= charity.address2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= charity.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= charity.state %>
  </p>

  <p>
    <strong>Postal code:</strong>
    <%= charity.postal_code %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= charity.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= charity.email %> <i class="fas fa-envelope"></i>
  </p>

  <p>
    <strong>Website:</strong>
    <%= charity.website %>
  </p>

  <p>
    <strong>Published:</strong>
    <%= charity.published %>
  </p>

  <p>
    <strong>Approved:</strong>
    <%= charity.approved %>
  </p>
  <p>
  <%= link_to image_tag(charity.logo, style:"width:150px; height:150px"), charity.logo if charity.logo.attached? %>
  </p>

  <p>
  <% charity.images.each do |image| %>
    <%= link_to image_tag(image, style:"width:150px; height:auto"), image %>
  <% end %>
  </p>
</div>

app/views/charities/_form.html.erb
  <% if charity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
        <% charity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for charity do |form| %>
    <%= form.input :title %>
    <%= form.input :tax_id_number %>
    <%= form.input :tax_exempt_status %>
    <%= form.input :organization_type %>
    <%= form.input :mission %>
    <%= form.rich_text_area :description %>
    <%= form.input :address1 %>
    <%= form.input :address2 %>
    <%= form.input :city %>
    <%= form.input :state %>
    <%= form.input :postal_code %>
    <%= form.input :phone %>
    <%= form.input :email %>
    <%= form.input :website %>
    <%= form.input :published %>
    <%= form.input :approved %>
    <%= form.file_field :logo %>
    <%= form.file_field :images, multiple: true %>
    <%= form.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render "form", charity: @charity %>

<br>

<div>
  <%= link_to "Show this charity", @charity %> |
  <%= link_to "Back to charities", charities_path %>
</div>

app/views/charities/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<header>
  <h1>All Charities</h1>

  <ul class="actions">
    <li><%= link_to "New Charity", new_charity_path, class: "new" %></li>
  </ul>
</header>

<div class="row">

  <div class="col-sm-3 pull-right"></div>
  <div class="sidebar">
    <h3 class="discover">Discover</h3>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= "active" if current_page?("/charities") %>"><%= link_to "All Charities" %> </li>
    </ul>
  </div>
</div>

<body>

<div>
<%# bootstrap icon %>
  <i class="bi-alarm" style="font-size: 2rem; color: cornflowerblue;"></i>
  <i class="bi-award"></i>
  <i class="bi-droplet"></i>
<%# font awesome icons %>
  <i class="fas fa-plus"></i>
  <i class="fas fa-basketball-ball"></i>
  <i class="far fa-check-square"></i>
</div>

<div>
  <button type="button"
          class="btn btn-lg btn-danger"
          data-bs-toggle="popover"
          title="Popover title"
          data-bs-content="Amazing content, right ?">
          Click to toggle popover
  </button>
</div>
<p>
<p>
<button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Top popover">
  Popover on top
</button>
<button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Right popover">
  Popover on right
</button>
<button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Bottom popover">
  Popover on bottom
</button>
<button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="left" data-bs-content="Left popover">
  Popover on left
</button>
<p>
<div>
  <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
    Tooltip on top
  </button>
  <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="right" title="Tooltip on right">
    Tooltip on right
  </button>
  <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on bottom">
    Tooltip on bottom
  </button>
  <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="left" title="Tooltip on left">
    Tooltip on left
  </button>
  <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
    Tooltip with HTML
  </button>
</div>
<p>
<div>
<!-- Button trigger modal -->
 <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Modal content
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<p>
<div id="charities">
  <% @charities.each do |charity| %>
    <%= render charity %>
    <p>
      <%= link_to "Edit charity", edit_charity_path(charity) %> |
      <%= link_to "Delete charity", charity_path(charity), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </p>
  <% end %>
</div>
</body>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render "form", charity: @charity %>

<br>

<div>
  <%= link_to "Back to charities", charities_path %>
</div>

app/views/charities/show.html.erb
<% provide(:title, @charity.title) %>

<h1><%= @charity.title %></h1>

<div>
  <p><%= @charity.tax_id_number %></p>
  <p><%= @charity.tax_exempt_status %></p>
  <p><%= @charity.organization_type %></p>
  <p><%= @charity.mission %></p>
  <p><%= @charity.description %></p>
  <p><%= @charity.address1 %></p>
  <p><%= @charity.address2 %></p>
  <p><%= @charity.city %></p>
  <p><%= @charity.state %></p>
  <p><%= @charity.postal_code %></p>
  <p><%= @charity.phone %></p>
  <p><%= @charity.email %></p>
  <p><%= @charity.website %></p>
  <p><%= @charity.approved %></p>
  <p><%= link_to image_tag(@charity.logo, style:"width:150px; height:150px"), @charity.logo if @charity.logo.attached? %></p>
  <p><% @charity.images.each do |image| %> 
     <%= link_to image_tag(image, style:"width:150px; height:auto"), image %>
     <% end %>
  </p>
</div>

<div>
  <%= link_to "Back to charities", charities_path %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CharityPlaza™</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Charities</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Volunteer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Jobs</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            About
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">About Us</a></li>
            <li><a class="dropdown-item" href="#">FAQ</a></li>
            <li><a class="dropdown-item" href="#">Contact Us</a></li>
          </ul>
        </li>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "layouts/header"%>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type%>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>